apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ${PV_NAME}
  namespace: ${NAMESPACE}
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: efs-static
  resources:
    requests:
      storage: ${SIZE}
  volumeName: ${PV_NAME}